name: Update Playlist Every 4 Hours

on:
  schedule:
    - cron: cron: '*/18 * * * *' # Runs every 18 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (addinm3u branch)
        uses: actions/checkout@v3
        with:
          ref: addinm3u # Checkout addinm3u branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.FANTOKEN }}
        run: |
          python update_playlist.py
